"""
Active Cyber Deception with LLM-Generated Lures
Database Schema Definition — SQLAlchemy Models

SECURITY NOTE:
  - All content stored in this database is SYNTHETIC.
  - No real credentials, IP addresses, or configuration should ever be stored.
  - is_synthetic field is enforced as True for all lure records.
"""

from datetime import datetime
from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Integer, JSON, String, Text, create_engine, event
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()


class Attacker(Base):
    """
    Represents a detected entity interacting with the deception environment.
    One record per unique session (proxied by IP + User-Agent combination).
    """
    __tablename__ = "attackers"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(36), unique=True, nullable=False, index=True)  # UUID
    source_ip = Column(String(45), nullable=False)  # IPv4 or IPv6
    user_agent = Column(String(500), nullable=True)
    first_seen = Column(DateTime, nullable=False, default=datetime.utcnow)
    last_seen = Column(DateTime, nullable=False, default=datetime.utcnow)
    risk_score = Column(Float, default=0.0)
    behavior_type = Column(String(50), nullable=True)  # e.g., RECONNAISSANCE
    status = Column(String(20), default="active")  # active | inactive | blocked

    # Relationships
    events = relationship("Event", back_populates="attacker",
                          foreign_keys="Event.session_id",
                          primaryjoin="Attacker.session_id == Event.session_id")
    attack_sessions = relationship("AttackSession", back_populates="attacker",
                                   foreign_keys="AttackSession.session_id",
                                   primaryjoin="Attacker.session_id == AttackSession.session_id")
    lure_interactions = relationship("LureInteraction", back_populates="attacker",
                                     foreign_keys="LureInteraction.session_id",
                                     primaryjoin="Attacker.session_id == LureInteraction.session_id")


class Event(Base):
    """
    Every HTTP request to the deception environment is recorded as an Event.
    Events are the raw material for detection, risk scoring and classification.
    """
    __tablename__ = "events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(36), ForeignKey("attackers.session_id"),
                        nullable=False, index=True)
    event_type = Column(String(50), nullable=False)   # e.g., SUSPICIOUS_REQUEST
    endpoint = Column(String(500), nullable=False)
    method = Column(String(10), nullable=False)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    severity = Column(String(20), nullable=False)     # LOW | MEDIUM | HIGH | CRITICAL
    metadata_ = Column("metadata", JSON, nullable=True)  # headers, query params, etc.
    is_suspicious = Column(Boolean, default=False)
    risk_delta = Column(Float, default=0.0)           # Risk score contributed by this event

    # Relationships
    attacker = relationship("Attacker", back_populates="events",
                            foreign_keys=[session_id],
                            primaryjoin="Event.session_id == Attacker.session_id")


class Lure(Base):
    """
    A synthetic deception artifact generated by the LLM or Mock provider.
    ALL content in this table is SYNTHETIC — never real credentials or configs.
    """
    __tablename__ = "lures"

    id = Column(Integer, primary_key=True, autoincrement=True)
    lure_id = Column(String(36), unique=True, nullable=False, index=True)  # UUID
    lure_type = Column(String(50), nullable=False)
    # Types: fake_credentials | fake_config | fake_document | fake_api_doc | fake_backup
    title = Column(String(200), nullable=False)
    content = Column(Text, nullable=False)
    target_interest = Column(String(50), nullable=False)
    generated_by = Column(String(50), nullable=False)  # ollama | openai | mock
    created_at = Column(DateTime, default=datetime.utcnow)
    deployed_at = Column(DateTime, nullable=True)
    status = Column(String(20), default="generated")  # generated | deployed | retired
    endpoint_path = Column(String(200), nullable=True)
    confidence = Column(Float, nullable=True)
    validation_passed = Column(Boolean, default=False)
    # SECURITY: This must ALWAYS be True. Enforced in application logic.
    is_synthetic = Column(Boolean, default=True, nullable=False)

    # Relationships
    interactions = relationship("LureInteraction", back_populates="lure",
                                foreign_keys="LureInteraction.lure_id",
                                primaryjoin="Lure.lure_id == LureInteraction.lure_id")


class LureInteraction(Base):
    """
    Records each time a simulated attacker accesses a deployed lure.
    Used to measure lure effectiveness.
    """
    __tablename__ = "lure_interactions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    lure_id = Column(String(36), ForeignKey("lures.lure_id"),
                     nullable=False, index=True)
    session_id = Column(String(36), ForeignKey("attackers.session_id"),
                        nullable=False, index=True)
    interaction_type = Column(String(50), nullable=False)  # VIEW | DOWNLOAD | SUBMIT
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    time_spent_seconds = Column(Float, nullable=True)
    metadata_ = Column("metadata", JSON, nullable=True)

    # Relationships
    lure = relationship("Lure", back_populates="interactions",
                        foreign_keys=[lure_id],
                        primaryjoin="LureInteraction.lure_id == Lure.lure_id")
    attacker = relationship("Attacker", back_populates="lure_interactions",
                            foreign_keys=[session_id],
                            primaryjoin="LureInteraction.session_id == Attacker.session_id")


class AttackSession(Base):
    """
    High-level session record tracking the progression of an attacker's campaign.
    Attack stages: RECONNAISSANCE → RESOURCE_DISCOVERY → CONFIGURATION_DISCOVERY
                   → CREDENTIAL_DISCOVERY → LURE_INTERACTION → CREDENTIAL_ATTEMPT
    """
    __tablename__ = "attack_sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(36), ForeignKey("attackers.session_id"),
                        nullable=False, index=True)
    started_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    ended_at = Column(DateTime, nullable=True)
    risk_score = Column(Float, default=0.0)
    attack_stage = Column(String(50), default="RECONNAISSANCE")
    total_events = Column(Integer, default=0)
    suspicious_events = Column(Integer, default=0)
    lures_generated = Column(Integer, default=0)
    lures_interacted = Column(Integer, default=0)

    # Relationships
    attacker = relationship("Attacker", back_populates="attack_sessions",
                            foreign_keys=[session_id],
                            primaryjoin="AttackSession.session_id == Attacker.session_id")


class LLMGeneration(Base):
    """
    Audit log of every LLM generation request.
    Tracks prompts, outputs, and validation results for transparency and debugging.
    SECURITY: Input context must never contain raw user input.
    """
    __tablename__ = "llm_generations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    generation_id = Column(String(36), unique=True, nullable=False)  # UUID
    prompt_template = Column(String(100), nullable=False)
    model = Column(String(100), nullable=False)
    input_context = Column(JSON, nullable=False)     # Sanitized context sent to LLM
    output = Column(JSON, nullable=True)             # Structured LLM response
    validation_status = Column(String(20), nullable=False)  # pending | passed | failed
    validation_errors = Column(JSON, nullable=True)  # List of validation error messages
    created_at = Column(DateTime, default=datetime.utcnow)
    processing_time_ms = Column(Float, nullable=True)
    session_id = Column(String(36), nullable=True, index=True)
