import React, { useState } from 'react';
import { FileCode, CheckCircle2, ShieldCheck, ExternalLink, Copy } from 'lucide-react';
import { deployLure } from '../services/api';

export default function Lures({ lures, onRefresh }) {
  const [selectedLure, setSelectedLure] = useState(null);
  const [copied, setCopied] = useState(false);

  const handleDeploy = async (lureId) => {
    try {
      await deployLure(lureId);
      onRefresh();
    } catch (e) {
      alert(`Failed to deploy: ${e.message}`);
    }
  };

  const copyContent = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div>
        <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#f8fafc' }}>LLM Lure Vault</h1>
        <p style={{ color: '#94a3b8', fontSize: '14px', marginTop: '4px' }}>
          Autonomous synthetic artifacts generated by the LLM, validated for security, and deployed to entice attackers.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: selectedLure ? '1fr 1fr' : '1fr', gap: '24px' }}>
        {/* Lure Cards Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: selectedLure ? '1fr' : 'repeat(3, 1fr)', gap: '16px' }}>
          {(lures || []).map((lure) => (
            <div
              key={lure.lure_id}
              className="glass-card"
              onClick={() => setSelectedLure(lure)}
              style={{
                padding: '20px',
                cursor: 'pointer',
                border: selectedLure?.lure_id === lure.lure_id ? '1px solid #38bdf8' : '1px solid var(--border-color)',
                background: selectedLure?.lure_id === lure.lure_id ? 'rgba(56, 189, 248, 0.08)' : 'var(--bg-card)'
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <FileCode style={{ width: '18px', height: '18px', color: '#38bdf8' }} />
                  <span className="mono" style={{ fontSize: '14px', fontWeight: '700', color: '#f8fafc' }}>{lure.title}</span>
                </div>
                <span style={{
                  fontSize: '11px',
                  padding: '2px 8px',
                  borderRadius: '4px',
                  fontWeight: '600',
                  background: lure.status === 'deployed' ? 'rgba(16, 185, 129, 0.2)' : 'rgba(245, 158, 11, 0.2)',
                  color: lure.status === 'deployed' ? '#10b981' : '#f59e0b'
                }}>
                  {lure.status.toUpperCase()}
                </span>
              </div>

              <p style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '14px' }}>
                Target Interest: <strong style={{ color: '#e2e8f0' }}>{lure.target_interest}</strong>
              </p>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '12px', borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '12px' }}>
                <span style={{ color: '#64748b' }}>Provider: {lure.generated_by}</span>
                <span style={{ color: '#10b981', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <ShieldCheck style={{ width: '14px', height: '14px' }} /> SYNTHETIC
                </span>
              </div>
            </div>
          ))}
        </div>

        {/* Selected Lure Viewer */}
        {selectedLure && (
          <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <h3 className="mono" style={{ fontSize: '18px', color: '#38bdf8' }}>{selectedLure.title}</h3>
                <span style={{ fontSize: '12px', color: '#94a3b8' }}>Path: {selectedLure.endpoint_path}</span>
              </div>
              {selectedLure.status !== 'deployed' && (
                <button
                  onClick={() => handleDeploy(selectedLure.lure_id)}
                  style={{
                    padding: '8px 16px',
                    borderRadius: '6px',
                    background: '#10b981',
                    color: 'white',
                    border: 'none',
                    fontWeight: '600',
                    cursor: 'pointer'
                  }}
                >
                  Deploy to Gateway
                </button>
              )}
            </div>

            <div style={{ position: 'relative' }}>
              <pre className="mono" style={{
                background: '#090d16',
                padding: '16px',
                borderRadius: '8px',
                fontSize: '13px',
                color: '#38bdf8',
                overflowX: 'auto',
                border: '1px solid rgba(255,255,255,0.08)',
                maxHeight: '350px'
              }}>
                {selectedLure.content}
              </pre>
              <button
                onClick={() => copyContent(selectedLure.content)}
                style={{
                  position: 'absolute',
                  top: '10px',
                  right: '10px',
                  padding: '6px 10px',
                  background: 'rgba(30, 41, 59, 0.8)',
                  color: '#94a3b8',
                  border: '1px solid var(--border-color)',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '12px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px'
                }}
              >
                <Copy style={{ width: '12px', height: '12px' }} /> {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
