import React, { useState } from 'react';
import { 
  FileCode, 
  CheckCircle2, 
  ShieldCheck, 
  ExternalLink, 
  Copy, 
  Plus, 
  Sparkles, 
  X, 
  Filter, 
  Globe 
} from 'lucide-react';
import { deployLure, generateLure } from '../services/api';

const INTERESTS = [
  { id: 'database', label: 'Database Credentials & Config' },
  { id: 'credentials', label: 'Admin & API Credentials' },
  { id: 'configuration', label: 'Environment & Server Config' },
  { id: 'admin', label: 'Internal Admin Panel Secrets' },
  { id: 'backup', label: 'Backup Archive Credentials' },
  { id: 'reconnaissance', label: 'Reconnaissance Lure' },
];

export default function Lures({ lures, onRefresh }) {
  const [selectedLure, setSelectedLure] = useState(null);
  const [copied, setCopied] = useState(false);
  const [filterStatus, setFilterStatus] = useState('ALL');
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedInterest, setSelectedInterest] = useState('database');
  const [generating, setGenerating] = useState(false);
  const [customPath, setCustomPath] = useState('');
  const [statusMsg, setStatusMsg] = useState(null);

  const handleDeploy = async (lureId, endpointPath) => {
    try {
      await deployLure(lureId, endpointPath || null);
      setStatusMsg("Lure deployed to gateway successfully!");
      onRefresh();
      if (selectedLure?.lure_id === lureId) {
        setSelectedLure(prev => prev ? { ...prev, status: 'deployed', endpoint_path: endpointPath || prev.endpoint_path } : null);
      }
    } catch (e) {
      alert(`Failed to deploy: ${e.message}`);
    }
  };

  const handleCreateLure = async () => {
    setGenerating(true);
    try {
      const newLure = await generateLure(null, selectedInterest);
      setShowCreateModal(false);
      setStatusMsg(`Successfully generated synthetic lure "${newLure.title}"!`);
      onRefresh();
      setSelectedLure(newLure);
    } catch (e) {
      alert(`Generation failed: ${e.message}`);
    } finally {
      setGenerating(false);
    }
  };

  const copyContent = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const filteredLures = (lures || []).filter(l => {
    if (filterStatus === 'ALL') return true;
    return l.status.toUpperCase() === filterStatus;
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#f8fafc' }}>LLM Lure Vault</h1>
          <p style={{ color: '#94a3b8', fontSize: '14px', marginTop: '4px' }}>
            Autonomous synthetic artifacts generated by the LLM, validated for security, and deployed to deceive adversaries.
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          {/* Status Filter */}
          <div style={{ display: 'flex', background: 'rgba(30, 41, 59, 0.6)', padding: '4px', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
            {['ALL', 'DEPLOYED', 'GENERATED'].map(status => (
              <button
                key={status}
                onClick={() => setFilterStatus(status)}
                style={{
                  padding: '6px 12px',
                  borderRadius: '6px',
                  border: 'none',
                  background: filterStatus === status ? 'rgba(56, 189, 248, 0.2)' : 'transparent',
                  color: filterStatus === status ? '#38bdf8' : '#94a3b8',
                  fontSize: '12px',
                  fontWeight: '600',
                  cursor: 'pointer'
                }}
              >
                {status}
              </button>
            ))}
          </div>

          <button
            onClick={() => setShowCreateModal(true)}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              padding: '9px 16px',
              borderRadius: '8px',
              background: 'linear-gradient(135deg, #0284c7, #38bdf8)',
              color: 'white',
              border: 'none',
              fontWeight: '600',
              fontSize: '13px',
              cursor: 'pointer',
              boxShadow: '0 0 15px rgba(56, 189, 248, 0.25)'
            }}
          >
            <Plus style={{ width: '16px', height: '16px' }} /> Generate Synthetic Lure
          </button>
        </div>
      </div>

      {statusMsg && (
        <div style={{ padding: '12px 16px', background: 'rgba(16, 185, 129, 0.15)', border: '1px solid #10b981', color: '#10b981', borderRadius: '8px', fontSize: '14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span>✔ {statusMsg}</span>
          <button onClick={() => setStatusMsg(null)} style={{ background: 'none', border: 'none', color: '#10b981', cursor: 'pointer' }}>✕</button>
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: selectedLure ? '1fr 1fr' : '1fr', gap: '24px' }}>
        {/* Lure Cards Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: selectedLure ? '1fr' : 'repeat(3, 1fr)', gap: '16px' }}>
          {filteredLures.map((lure) => (
            <div
              key={lure.lure_id}
              className="glass-card"
              onClick={() => setSelectedLure(lure)}
              style={{
                padding: '20px',
                cursor: 'pointer',
                border: selectedLure?.lure_id === lure.lure_id ? '1px solid #38bdf8' : '1px solid var(--border-color)',
                background: selectedLure?.lure_id === lure.lure_id ? 'rgba(56, 189, 248, 0.08)' : 'var(--bg-card)',
                transition: 'all 0.2s'
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <FileCode style={{ width: '18px', height: '18px', color: '#38bdf8' }} />
                  <span className="mono" style={{ fontSize: '14px', fontWeight: '700', color: '#f8fafc' }}>{lure.title}</span>
                </div>
                <span style={{
                  fontSize: '11px',
                  padding: '2px 8px',
                  borderRadius: '4px',
                  fontWeight: '600',
                  background: lure.status === 'deployed' ? 'rgba(16, 185, 129, 0.2)' : 'rgba(245, 158, 11, 0.2)',
                  color: lure.status === 'deployed' ? '#10b981' : '#f59e0b'
                }}>
                  {lure.status.toUpperCase()}
                </span>
              </div>

              <p style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '14px' }}>
                Target Interest: <strong style={{ color: '#e2e8f0' }}>{lure.target_interest}</strong>
              </p>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '12px', borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '12px' }}>
                <span style={{ color: '#64748b' }}>Provider: {lure.generated_by}</span>
                <span style={{ color: '#10b981', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <ShieldCheck style={{ width: '14px', height: '14px' }} /> SYNTHETIC
                </span>
              </div>
            </div>
          ))}
        </div>

        {/* Selected Lure Viewer */}
        {selectedLure && (
          <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div>
                <h3 className="mono" style={{ fontSize: '18px', color: '#38bdf8' }}>{selectedLure.title}</h3>
                <div style={{ fontSize: '12px', color: '#94a3b8', marginTop: '4px' }}>
                  Target Interest: <strong style={{ color: '#f8fafc' }}>{selectedLure.target_interest}</strong> | Type: {selectedLure.lure_type}
                </div>
              </div>
              <button
                onClick={() => setSelectedLure(null)}
                style={{ background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: '16px' }}
              >
                ✕
              </button>
            </div>

            {/* Path and Deployment Info */}
            <div style={{ background: 'rgba(15, 23, 42, 0.7)', padding: '14px', borderRadius: '8px', border: '1px solid var(--border-color)', display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '12px', color: '#94a3b8' }}>Deployed Gateway Endpoint:</span>
                {selectedLure.status === 'deployed' ? (
                  <a
                    href={`http://127.0.0.1:8000/gateway${selectedLure.endpoint_path.startsWith('/') ? selectedLure.endpoint_path : `/${selectedLure.endpoint_path}`}`}
                    target="_blank"
                    rel="noreferrer"
                    style={{ fontSize: '12px', color: '#38bdf8', display: 'flex', alignItems: 'center', gap: '4px', textDecoration: 'none' }}
                  >
                    <Globe style={{ width: '13px', height: '13px' }} /> View on Live Gateway <ExternalLink style={{ width: '12px', height: '12px' }} />
                  </a>
                ) : (
                  <span style={{ fontSize: '12px', color: '#f59e0b' }}>Not yet active on gateway</span>
                )}
              </div>
              <div className="mono" style={{ fontSize: '12px', color: '#38bdf8', wordBreak: 'break-all' }}>
                {selectedLure.endpoint_path}
              </div>
            </div>

            {/* Action Bar */}
            <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
              {selectedLure.status !== 'deployed' ? (
                <button
                  onClick={() => handleDeploy(selectedLure.lure_id, customPath || selectedLure.endpoint_path)}
                  style={{
                    flex: 1,
                    padding: '10px 16px',
                    borderRadius: '6px',
                    background: '#10b981',
                    color: 'white',
                    border: 'none',
                    fontWeight: '600',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '8px'
                  }}
                >
                  <CheckCircle2 style={{ width: '16px', height: '16px' }} /> Deploy to Gateway
                </button>
              ) : (
                <div style={{ flex: 1, padding: '8px 14px', borderRadius: '6px', background: 'rgba(16, 185, 129, 0.15)', border: '1px solid rgba(16, 185, 129, 0.3)', color: '#10b981', fontSize: '12px', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 style={{ width: '14px', height: '14px' }} /> Active Deception Artifact
                </div>
              )}
            </div>

            {/* Lure Content Preview */}
            <div style={{ position: 'relative' }}>
              <pre className="mono" style={{
                background: '#090d16',
                padding: '16px',
                borderRadius: '8px',
                fontSize: '13px',
                color: '#38bdf8',
                overflowX: 'auto',
                border: '1px solid rgba(255,255,255,0.08)',
                maxHeight: '350px'
              }}>
                {selectedLure.content}
              </pre>
              <button
                onClick={() => copyContent(selectedLure.content)}
                style={{
                  position: 'absolute',
                  top: '10px',
                  right: '10px',
                  padding: '6px 10px',
                  background: 'rgba(30, 41, 59, 0.8)',
                  color: '#94a3b8',
                  border: '1px solid var(--border-color)',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '12px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px'
                }}
              >
                <Copy style={{ width: '12px', height: '12px' }} /> {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Generator Modal */}
      {showCreateModal && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100vw',
          height: '100vh',
          background: 'rgba(0, 0, 0, 0.75)',
          backdropFilter: 'blur(8px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 100
        }}>
          <div className="glass-card" style={{
            width: '500px',
            background: '#0f172a',
            border: '1px solid var(--border-color)',
            padding: '28px',
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
            boxShadow: '0 20px 50px rgba(0,0,0,0.5)'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#38bdf8' }}>
                <Sparkles style={{ width: '18px', height: '18px' }} />
                <h3 style={{ fontSize: '18px', color: '#f8fafc', margin: 0 }}>Generate Synthetic Lure</h3>
              </div>
              <button
                onClick={() => setShowCreateModal(false)}
                style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: '18px' }}
              >
                ✕
              </button>
            </div>

            <p style={{ fontSize: '13px', color: '#94a3b8', margin: 0 }}>
              The LLM engine will generate a highly realistic, fully synthetic deception asset with embedded watermarks and honey-tokens.
            </p>

            <div>
              <label style={{ fontSize: '12px', fontWeight: '600', color: '#e2e8f0', display: 'block', marginBottom: '8px' }}>
                TARGET ADVERSARY INTEREST:
              </label>
              <select
                value={selectedInterest}
                onChange={(e) => setSelectedInterest(e.target.value)}
                style={{
                  width: '100%',
                  padding: '10px 14px',
                  borderRadius: '6px',
                  background: 'rgba(30, 41, 59, 0.8)',
                  border: '1px solid var(--border-color)',
                  color: '#f8fafc',
                  fontSize: '13px',
                  outline: 'none'
                }}
              >
                {INTERESTS.map(item => (
                  <option key={item.id} value={item.id}>{item.label}</option>
                ))}
              </select>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '10px' }}>
              <button
                onClick={() => setShowCreateModal(false)}
                style={{
                  padding: '9px 16px',
                  borderRadius: '6px',
                  background: 'transparent',
                  border: '1px solid var(--border-color)',
                  color: '#94a3b8',
                  fontSize: '13px',
                  cursor: 'pointer'
                }}
              >
                Cancel
              </button>
              <button
                disabled={generating}
                onClick={handleCreateLure}
                style={{
                  padding: '9px 20px',
                  borderRadius: '6px',
                  background: 'linear-gradient(135deg, #0284c7, #38bdf8)',
                  color: 'white',
                  border: 'none',
                  fontWeight: '600',
                  fontSize: '13px',
                  cursor: generating ? 'not-allowed' : 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                <Sparkles style={{ width: '15px', height: '15px' }} />
                {generating ? 'Synthesizing Lure...' : 'Generate Lure'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
